### ISSUE TITLE
Can't log in with my microsoft account

### ISSUE THREAD

**Issue by marcelovbcfilho** [flathub/io.mrarm.mcpelauncher#2]
When I try to log into my Microsoft account, the game doesn't prompt me to type my credentials and when I try again the game show me the following message.
![Captura de tela de 2020-07-14 15-47-22](https://user-images.githubusercontent.com/51462138/87464451-848b6080-c5e9-11ea-85bc-6281c3d21e0e.png)

**Comment by ChristopherHX** [comment]
**You're signed up to beta in google play and see an only partially working Minecraft beta, please consider opt out from beta.**, hiding betas completly (by default) is planned https://github.com/minecraft-linux/mcpelauncher-ui-manifest/issues/20

Known issue https://github.com/ChristopherHX/mcpelauncher-manifest/issues/104 , no xboxlive for now.

Please select the latest stable (as of Today) `Minecraft 1.16.1.02` or older to use xboxlive.

**Comment by riyogarta** [comment]
I have the same problem.
![Minecraft_693](https://user-images.githubusercontent.com/3301549/90019531-be2eb480-dcd8-11ea-8411-e9ec459b2a57.png)

Now, the stable version is 1.16.20.
Can you fix it? Thanks

**Comment by skewty** [comment]
I read on the associated Discord channel that @ChristopherHX is busy studying right now so we are all to be patient.

Perhaps if somebody has the "know how" to fix the Microsoft Sign-in issue coming up with v1.16.20 update they can do a PR an perhaps it can get up-streamed for all to benefit.

**Please**, for all reading this, follow proper usage guidelines and do a [thumbs up] on the above "I have the same problem." post instead of writing a new comment in this issue saying something along the lines of "me too" / "please fix this".

**Comment by ChristopherHX** [comment]
This will still take a lot of time to be available on flathub and easy to use.

Skilled people can try latest buggy stuff (1.16.20.03 x86_64 and Xboxlive works)
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/374#issuecomment-674563699
