### ISSUE TITLE
How to fix the rendering issues... 

### ISSUE THREAD

**Issue by Haus3master** [flathub/io.mrarm.mcpelauncher#28]
I'm on raspberry Pi OS 32 bit on the Pi3B+ and I have noticed that the game has rendering issues, a fix was provided for the appimage by downgrading mesa, but, trying something similar in the flatpak doesn't work, how do I fix it? 
Edit: I will post images in a few minutes for proof... 
Here are a few images with the rendering issues, a fix was documented for the raspberry Pis running the appimage version, but, I can't give a fix for the flatpak version...
(Also, the Dev mode enabling option --enable-devmode option isn't working on the appimage version but works on the flatpak one, that's why I'm using this launcher and asking if a workaround is possible...)
I also have fake kms enabled as suggested, and, disabling it causes the game to run at 7-8 fps on my pi 3b+
 ![Screenshot_20210322-202016.png](https://user-images.githubusercontent.com/66825701/112009040-0d30a800-8b4c-11eb-8e6a-90f410a61beb.png)

**Comment by ChristopherHX** [comment]
> a fix was documented for the raspberry Pis running the appimage version

You think this was a fix? It is more like a workaround for the discontinued opengles2 driver for RaspberryPi 2 and 3. I found it randomly while figuring out getting the original launcher to open on my raspberry Pi2, while on debian stretch it rendered fine it looks like your picture after updating to buster.

I think this could be done via an optional flatpak extension, with the old mesa 1.13 version. Still do you really need the flatpak version, it complicates everything.
Better report this bug to mesa and hope they fix the vc4 driver for the old raspberry Pi's, I haven't done that.

> --enable-devmode option isn't working on the appimage version

Oh this seems to be another arm only AppImage bug, because mcpelauncher-qt never had a cli before.
You know bash? If you would like make a PR to preserve the cli parameters in https://github.com/ChristopherHX/linux-packaging-scripts/blob/main/AppRun this will work on arm AppImage too.

**Comment by Haus3master** [comment]
Could you please mention on what to do with the file? (I'm not very advanced and only use bash mostly due automation scripts...)

**Comment by ChristopherHX** [comment]
In the file is a call to `mcpelauncher-ui-qt`, you need to add the original parameters of the script to the call maybe `...mcpelauncher-ui-qt %*`

**Comment by Haus3master** [comment]
I'm sorry, but, I will wait for an update, this is too advanced for my knowing about bash...

**Comment by Haus3master** [comment]
I'm sorry, but, I will wait for an update, this is too advanced for my knowing about bash... 
Edit: I will wait, as, I'm not in any hurry and, also, I'm downloading stretch so that I can use the flatpak version on my Pi without the rendering issues, as you mentioned previously, the latest supported version can connect to realms, and, that's good for me to wait...

**Comment by ChristopherHX** [comment]
I as a flatpak maintainer should (technically) update the launcher sometime to a newer kde runtime, but it will implicitly remove the arm32 flatpak https://github.com/flathub/io.mrarm.mcpelauncher/pull/6.
Freedesktop has removed all 32bit architectures from their runtime, but the config doesn't allow me to specifiy multiple versions of the runtime.

**Comment by Haus3master** [comment]
> I as a flatpak maintainer should (technically) update the launcher sometime to a newer kde runtime, but it will implicitly remove the arm32 flatpak https://github.com/flathub/io.mrarm.mcpelauncher/pull/6.
> Freedesktop has removed all 32bit architectures from their runtime, but the config doesn't allow me to specifiy multiple versions of the runtime.

Oh, okay...
