### ISSUE TITLE
new update 1.16.220.52 does not work, on minecraft.

### ISSUE THREAD

**Issue by lol851** [flathub/io.mrarm.mcpelauncher#29]
this is what happened when I tried on Minecraft when I tried to get the newest update.
   
"You previously downloaded Minecraft Version might be unsupported or just corrupted.
if you wanted to play a Beta or a new Release please wait patiently for an update,
please choose a compatible version from the profile Editor
otherwise if you have updated the Launcher recently.
e.g. a crash please delete it in Settings,
then download it again via the updated Launcher."  

Is anybody having the same issue?

**Comment by ChristopherHX** [comment]
> Is anybody having the same issue?

**You have at least one update available, which fixes bugs**

1. Update the Launcher (`flatpak update` in terminal)
2. Stop Playing Beta, that is an unmaintainable feature.
  Betas are breaking stuff see here for the status of 1.16.220 https://github.com/ChristopherHX/mcpelauncher-manifest/issues/48#issuecomment-795472828
  This version won't work before 2021-5-2
3. The Launcher should show 1.16.210, if you haven't changed any Settings 
  - Even if you are in the beta program, the launcher downloads the last known working version (since v0.1-beta-21)

**Comment by lol851** [comment]
Ok thanks!
