### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by Nachowarrior** [flathub/io.mrarm.mcpelauncher#40]
For at least the last 2 releases, maybe 3, there have been rendering issues.  The lighting is utterly terrible for one, but worse yet, various blocks will not render the way they are supposed to.  eg: a wood block will be missing an entire side, ie: no bark on one edge of the block. This happens with a great variety of blocks including work stations.  another example is that the torches render as partially transparent. 

![image](https://user-images.githubusercontent.com/55152781/115932148-5b420f80-a45a-11eb-962a-e1fbeff6d286.png)

as you can see by the image, the torches have no shading and they do not even render correctly.

This comes with some parts of the world not rendering at all, ie: where there is a mountain, there will be a giant hole with nothing but blue sky behind it, when in fact, there are blocks. 

I don't know what the hell happened over the last few releases, but it's getting to be nearly unplayable at this juncture. At very least, it looks like trash compared to what it looked like a few months ago.

**Comment by ChristopherHX** [comment]
This is a game bug, affecting intel and amd based devices.
Also affects real x86 devices, running android x86.
https://bugs.mojang.com/browse/MCPE-121068

I'm not a opengles2 expert, there might be a complicated way to correct these things manually inside the launcher.
It is unlikly to be fixed by Mojang with the first release of 1.17. (beta 1.17.0.50 still has this bug).

The arm(64) build of this launcher doesn't suffer from this rendering and crafting problems like smartphones.

**Comment by Nachowarrior** [comment]
noted.  sent them (mojang) a 'nice' email regarding the ratio of income to the actual bug fixes they perform.   This game is ancient, and shouldn't suffer from these problems for the amount of income they generate.  Sort of pathetic that they're releasing updates with bugs built in, and then ignore them for months.
