### ISSUE TITLE
I cannot craft in LAN game

### ISSUE THREAD

**Issue by blauch** [flathub/io.mrarm.mcpelauncher#43]
I have joined LAN game but I cannot craft any items using the crafting table. I can add all the requires items but the crafted items have a red background. It is very annoying that I cannot craft myself. Please help!

**Comment by ChristopherHX** [comment]
This is a Minecraft Game bug, you have to ctrl+Right click at the item (in the item list, not the broken crafting grid). This bug is since December 2020 inside the game.

Why does it work on my phone? This bug only happens on intel/amd devices, if your phone would use this launcher crafting would work.

Workaround described by another person:
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/478#issuecomment-822441250

**Comment by blauch** [comment]
many thanks for the answer and the link to the workaround
